### ISSUE TITLE
Questions about answer annotation for the dataset test set.

### ISSUE THREAD

**Issue by zhousheng97** [bytedance/VTVQA#4]
Hello, 

In the link [https://github.com/bytedance/VTVQA/tree/master/Annotations ](url) you provided,  answers are not provided in the annotation file of the test set under three task settings, but the performance of the T5-VieVQA model on the test set is reported in the paper.  Could you please provide the test set annotation file with the answer?

**Comment by zhaominyiz** [comment]
Hi, I have provided the answers :)
